################### Filebeat Configuration Example #########################

############################# Filebeat ######################################
filebeat.input:
- type: log
  paths:
    - /var/log/messages
    - /var/log/secure
    - /var/log/iptables.log
  fields:
    document_type: sys_log
- type: log
  paths:
    - /var/log/audit/audit.log
  multiline:
    pattern: '^type=(SYSCALL|USER|CRYPTO|CRED)'
    negate: true
    match: after
  fields:
    document_type: auditd_log
- type: log
  paths:
    - "/var/log/yum.log"
  fields:
    document_type: yum_log
- type: log
  paths:
    - "/var/log/httpd/*access.log"
    - /var/log/httpd/access_log
    - "/var/log/httpd/*error.log"
    - /var/log/httpd/error_log
  fields:
    document_type: apache_log
- type: log
  paths:
    - /var/log/clamav/clamd.log
    - /var/log/clamd.scan
    - "/mnt/glusterfs/docker/volumes/fivium-clamav/logs/*/clamd.log"
  fields:
    document_type: clamav_log
- type: log
  paths:
    - /var/log/clamav/freshclam.log
  multiline:
    pattern: '^ClamAV update process'
    negate: true
    match: after
  fields:
    document_type: clamav_log
- type: log
  paths:
    - /var/log/maillog
  fields:
    document_type: mail_log
- type: log
  paths:
    - /opt/tomcat8/instances/*/logs/catalina.out
    - "/opt/tomcat8/instances/*/logs/catalina.*.log"
    - "/opt/tomcat8/instances/*/logs/localhost.*.log"
    - /opt/tomcat7/instances/*/logs/catalina.out
    - "/opt/tomcat7/instances/*/logs/catalina.*.log"
    - "/opt/tomcat7/instances/*/logs/localhost.*.log"
  multiline:
    pattern: '^\d{4}-\d{2}-\d{2}(T| )\d{2}:\d{2}:\d{2}(\.|\,)\d{3}(\+\d{4})?|^\d{2}(-|\/)\D{3}(-|\/)\d{4} \d{2}:\d{2}:\d{2}(,\d{3})?|^\w{3} \d{2}, \d{4} \d{1,2}:\d{2}:\d{2} (AM|PM)|^\d{7}\.\d{3}:'
    negate: true
    match: after
  fields:
    document_type: tomcat_log
- type: log
  paths:
    - "/oracle/diag/rdbms/*/*/trace/alert_*.log"
  multiline:
    pattern: '^\D{3} \D{3} \d{2} \d{2}:\d{2}:\d{2} \d{4}$'
    negate: true
    match: after
  fields:
    document_type: oracle_alert_log
- type: log
  paths:
    - "/oracle/diag/tnslsnr/*/listener/trace/listener.log"
  fields:
    document_type: oracle_listener_log
- type: log
  paths:
    - "/var/log/haproxy.log"
  fields:
    document_type: haproxy_log
- type: log
  paths:
    - "/var/log/vsftpd.log"
    - "/var/log/xferlog"
  fields:
    document_type: vsftpd_log
- type: log
  paths:
   - "/var/lib/docker/containers/*/*.log"
  fields:
    document_type: docker_log
  json.message_key: log
  json.keys_under_root: true
  processors:
  - add_docker_metadata: ~


# Multiple outputs may be used
### Logstash as output.
output.logstash:
  # The Logstash hosts
  hosts: ["logstash-server:5044"]
  # configure index prefix name
  index: filebeat


logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
